### ISSUE TITLE
Window cannot verify the digital signature for this file. A recent hardware or s oftware change might have installed a file that is signed incorrectly or damaged , or that might be malicious software from an unknown source.

### ISSUE THREAD

**Issue by penyaringan** [Mattiwatti/PPLKiller#11]
I'm testing PLLKiller on a fully patched and updated Windows 7 and Windows 10 x64 VMs. Did Microsoft updates break your work-around for the MS signed driver requirement?

**Comment by Mattiwatti** [comment]
Hi,

As far as I know the driver should still work as it always has, **if** test signing is enabled (or, like the README says, if you somehow have an EV certificate). Most likely you are test signing your driver (that means, signing it with a self-signed certificate) so you will need to run `bcdedit /set testsigning on` to be able to run it. If that doesn't help, please attach your compiled binary here in a ZIP so I can take a look at the certificate.

**Comment by Mattiwatti** [comment]
Did you manage to get this resolved?

**Comment by penyaringan** [comment]
I just tested a fresh build on the same VM and still get a digital signature verificaiton error when I run sc start pplkiller. I ran bcdedit /set testsigning on prior to installing the service. 

pplkiller64.sys attached as a .zip. I'm testing on x64 Win10 (10.0.17134.523).  Thanks for checking.
[release.zip](https://github.com/Mattiwatti/PPLKiller/files/2826957/release.zip)

**Comment by Mattiwatti** [comment]
Did you reboot after running `bcdedit /set testsigning on`? There should be a watermark in the bottom right of your screen that tells you test signing is enabled.

I tried your driver and it works on my VirtualBox Windows 10 RS5 VM that I just ran Windows Update on. Here it is working, with the watermark highlighted:
![testmode](https://i.imgur.com/cNPpKnm.png)

**Comment by Mattiwatti** [comment]
OK, good to hear you got it working.

To 'kill AV products' you are going to need something a bit more nuclear than this :smile: Remember that they are (or should be) designed to detect and block even kernel mode rootkits, so PPL protection is merely an additional convenient layer against user mode attacks, but I do not expect that any AV products truly rely on it. Also keep in mind that [ObRegisterCallbacks](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-obregistercallbacks), which has existed since Vista, is in principle a superset of PPL protection in that you can recreate the kernel's PPL implementation entirely even on older OSes using only object callbacks.

Will close this now as the original issue has been resolved.
