### ISSUE TITLE
restoring ppl

### ISSUE THREAD

**Issue by beranos** [Mattiwatti/PPLKiller#18]
hi very nice project, i'm wondering if after killing PPL if it's possible to restore it? if yes how can i do that?
thanks

**Comment by Mattiwatti** [comment]
This is not possible in PPLKiller by design, however you can implement it yourself if you want to.

The reason PPLKiller does not restore process protection is that PPL is a protection mechanism that is supposed to be active from the start of the life of a process until its end. If you undo this protection (as PPLKiller does), no guarantees can be made about the internal state or security of any processes that were "reprotected" (protected - sure... but after you did what with them?)

If you want to "reprotect" processes at some point, you should simply keep a list of processes that you have unprotected together with their original protection values. You can then restore these in `DriverUnload` or whichever call best suits your needs.

**Comment by beranos** [comment]
ok thank you for the reply, i've been trying this for a while but after 20-30 minutes of having the ppl of processes killed by pc bsods. i'm on windows 1909

**Comment by Mattiwatti** [comment]
Your BSOD is a PatchGuard bugcheck. In short this means that the kernel has detected that you have removed the protection on some process(es), and it does not like this. This is actually the first PatchGuard bugcheck caused by PPLKiller that I've seen, but I just tested this in a VM and was able to reproduce the crash on the latest kernel version pretty quickly.

I've updated the README with some information on how to deal with this, as this was not an issue on previous versions of Windows 10 or 8.1.
