### ISSUE TITLE
Cannot Test Sign the Driver

### ISSUE THREAD

**Issue by fatrolls** [Mattiwatti/PPLKiller#8]
I added /debug to command line of Driver Signing.

Here is what I get 

```
1>------ Build started: Project: PPLKiller, Configuration: Debug x64 ------
1>Building 'PPLKiller' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>PPLKiller.vcxproj -> C:\Users\Igor\Tools\PPLKiller-master\bin\pplkiller.sys
1>
1>The following certificates were considered:
1>SIGNTASK : SignTool error : No certificates were found that met all the given criteria.
1>    Issued to: 83410C25-192B-4952-B63B-D89C5F2C6AD6
1>
1>    Issued by: Apple iPhone Device CA
1>
1>    Expires:   Thu Oct 26 04:38:38 2017
1>
1>    SHA1 hash: 9B1D9443CDEACADF3C2BAE1F9841AB4435298927
1>
1>
1>    Issued to: WDKTestCert Igor,131657141306330865
1>
1>    Issued by: WDKTestCert Igor,131657141306330865
1>
1>    Expires:   Wed Mar 15 20:00:00 2028
1>
1>    SHA1 hash: 1F326A338F1C73EFB0CBA345205044CAAD69931E
1>
1>
1>After EKU filter, 1 certs were left.
1>After expiry filter, 1 certs were left.
1>After Hash filter, 1 certs were left.
1>After Private Key filter, 0 certs were left.
1>Done building project "PPLKiller.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

![screenshot 1 png](https://user-images.githubusercontent.com/8261488/40898686-ffb2b786-6790-11e8-9f7f-fd444d9c106b.png)

![screenshot 2 png](https://user-images.githubusercontent.com/8261488/40898707-225cd050-6791-11e8-9ef2-c3d2303d9734.png)

I guess the error is from the Apple iPhone Device CA I assume that comes from another tool which I used to jailbreak apple iphone.

**Comment by fatrolls** [comment]
Fixed it

![screenshot 1 png 1](https://user-images.githubusercontent.com/8261488/40898797-7ceaf56a-6791-11e8-8942-f1e03c725559.png)



```
1>------ Build started: Project: PPLKiller, Configuration: Debug x64 ------
1>Building 'PPLKiller' with toolset 'WindowsKernelModeDriver10.0' and the 'Desktop' target platform.
1>PPLKiller.vcxproj -> C:\Users\Igor\Tools\PPLKiller-master\bin\pplkiller.sys
1>
1>The following certificates were considered:
1>    Issued to: WDKTestCert Igor,131725614061133343
1>
1>    Issued by: WDKTestCert Igor,131725614061133343
1>
1>    Expires:   Sat Jun 03 20:00:00 2028
1>
1>    SHA1 hash: E2ABE094ACBD60E62732C9339E06E835751E4159
1>
1>
1>    Issued to: 83410C25-192B-4952-B63B-D89C5F2C6AD6
1>
1>    Issued by: Apple iPhone Device CA
1>
1>    Expires:   Thu Oct 26 04:38:38 2017
1>
1>    SHA1 hash: 9B1D9443CDEACADF3C2BAE1F9841AB4435298927
1>
1>
1>    Issued to: WDKTestCert Igor,131657141306330865
1>
1>    Issued by: WDKTestCert Igor,131657141306330865
1>
1>    Expires:   Wed Mar 15 20:00:00 2028
1>
1>    SHA1 hash: 1F326A338F1C73EFB0CBA345205044CAAD69931E
1>
1>
1>After EKU filter, 2 certs were left.
1>After expiry filter, 2 certs were left.
1>After Hash filter, 1 certs were left.
1>After Private Key filter, 1 certs were left.
1>The following certificate was selected:
1>    Issued to: WDKTestCert Igor,131725614061133343
1>
1>    Issued by: WDKTestCert Igor,131725614061133343
1>
1>    Expires:   Sat Jun 03 20:00:00 2028
1>
1>    SHA1 hash: E2ABE094ACBD60E62732C9339E06E835751E4159
1>
1>
1>Done Adding Additional Store
1>Successfully signed: C:\Users\Igor\Tools\PPLKiller-master\bin\pplkiller.sys
1>
1>
1>Number of files successfully Signed: 1
1>
1>Number of warnings: 0
1>
1>Number of errors: 0
1>
1>Inf2Cat task was skipped as there were no inf files to process
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
```

**Comment by fatrolls** [comment]
Now my computer crashes when I run the
sc start pplkiller

no blue screen of death just automatic restart out of the blue

**Comment by Mattiwatti** [comment]
Firstly, you are aware that PPLKiller does not support Windows 7? Windows 7 does not have PPLs and as such it does not need this driver. If you want to disable process protection on the System process, check out #5 (there isn't much point to this though as far as I'm aware, as stated in the thread.)

An automatic reboot likely actually **is** a BSOD, but with the Windows settings set to automatic restart (advanced system settings -> 'startup and recovery' -> checkbox 'automatically restart'). With this unchecked you should see the actual blue screen with the error code. In principle the driver is supposed to refuse to start on Windows 7 and earlier - i.e. it won't do anything, but it definitely shouldn't crash.

**Comment by fatrolls** [comment]
Is it not a protected process if you cannot attach a memory viewer to it or end task it and it only shows up as a service on API monitor/Process Explorer not a process, i'm talking about a game like EUDemons..

Thanks for the information.

**Comment by Mattiwatti** [comment]
What you mention could be caused by process protection, but given that you are on Windows 7 I would say this is highly unlikely. It is more likely that the game is being protected by [ObRegisterCallbacks](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-obregistercallbacks) as this is a much more flexible (not to mention supported and documented by MS) way to achieve the same. See also #6 where both process protection and `ObRegisterCallbacks` were being used together to protect the Windows Defender process in Windows 10. Try opening the process with `PROCESS_ALL_ACCESS` and compare this to the actual access mask on the handle you get back (viewable in e.g. Process Hacker or Process Explorer). Since you say you cannot kill the process, at the very least `PROCESS_TERMINATE` should be stripped from the handle access mask if `ObRegisterCallbacks` is being used.

If something shows up in the Process Explorer tree view, it's a process. This is not mutually exclusive with being a service: kernel mode drivers have a service entry in the registry but do not have an associated process (not counting certain functions such as `DriverEntry` which are guaranteed to run in the System process context). A process can be host to zero, one or multiple services. Most `svchost.exe`s are an example of the latter in Windows 7, though this process address space sharing has been mostly undone in Windows 10 where each `svchost.exe` hosts a single service.

There is an important difference between kernel mode and user mode services. A kernel mode service is really only barely a service in the traditional sense - it's mostly a convenient way for the system to store the information needed to load a driver. If you see a process associated with a service, that service is a user mode service. Finally, consider that:
- User mode processes (service or not) can load drivers so long as they have `SeLoadDriverPrivilege`.
- Kernel mode drivers can create both kernel and user mode threads in any process.
- Kernel mode drivers can create user mode processes and even new system processes.

These points (especially the last two) are mostly theoretical and are rarely done in practice (excepting kernel threads created in the System process). One example of a kernel mode thread running outside the System process is the `cdd.dll` thread in `csrss.exe`. The only Microsoft driver I'm aware of that creates processes is `condrv.sys`, which creates `conhost.exe` in Windows 8 and later.

**Comment by fatrolls** [comment]
Here is a image of the crash.

![img_20180608_210250](https://user-images.githubusercontent.com/8261488/41186186-2d867e0e-6b60-11e8-8154-8073d71e6569.jpg)

**Comment by Mattiwatti** [comment]
Your BSOD is caused by running a driver compiled for Windows 8.1 and later (project configuration -> Driver Settings -> General -> 'Target OS Version') on an older OS.

I guess I'll start by explaining what the blue screen means, since you obviously don't have a VM and/or a kernel debugger (or even kernel memory dumps for that matter...), and 'debug by BSOD' on live machines tends to not be a very good overall tactic when it comes to filesystem integrity, meaning you'll be reinstalling Windows soon if you keep this up.

Bugcheck `0x7E` is the generic catch-all `SYSTEM_THREAD_EXCEPTION_NOT_HANDLED`:
```
SYSTEM_THREAD_EXCEPTION_NOT_HANDLED      (0x7E)
PARAMETERS
    1 - The exception code that was not handled
        VALUES
        0x80000002: (STATUS_DATATYPE_MISALIGNMENT) An unaligned data reference was encountered.
                    The trap frame will supply additional information.
        0x80000003: This means a hard coded breakpoint or assertion was hit, but this system was booted
                    /NODEBUG.  This is not supposed to happen as developers should never have
                    hardcoded breakpoints in retail code, but ...
                    If this happens, make sure a debugger gets connected, and the
                    system is booted /DEBUG.  This will let us see why this breakpoint is
                    happening.
        END_VALUES
    2 - The address that the exception occurred at
    3 - Exception Record Address
    4 - Context Record Address
```
Parameter 1 (`0x80000003`) tells us this is a breakpoint.

Since the BSOD is kind enough to give us the address of the faulting instruction as well as the base of the driver, we can easily compute the RVA: `0xFFFFF8800723D279` - `0xFFFFF88007236000` = `0x7279`. If you check out this address in a disassembler such as IDA you will indeed find an `0xCC` byte (= `int 3` breakpoint).

However, the bugcheck description makes a fair point: breakpoints should be analyzed in a debugger because they aren't supposed to happen. I miscompiled the driver the same way you did to reproduce the result in a debugger attached to a Windows 7 machine:
![int3](https://i.imgur.com/KWZFmXz.png)
`GsDriverEntry` is the compiler-inserted entry point of the driver because the driver was compiled with `/GS` ('security check') enabled. I don't have much love for this switch, but it is the default setting and starting with Windows 8.1 Microsoft has made disabling it more trouble than it's worth, so it stays on.

As you can see `GsDriverEntry` calls `__security_init_cookie` and then transfers control to the actual `DriverEntry` function that can be found in the project source code. What's happening here? The value of `__security_cookie` is checked to ensure it is **not** `0x2B992DDFA232`, negated and the result stored in `__security_cookie_complement`. That's it. However, if the value **is** `0x2B992DDFA232` (which it is), the function performs a double kill:
- First it executes `RtlFailFast(6)` via interrupt `0x29`. This has no effect on your machine because this feature was introduced in Windows 8. If you were running Windows 8.0, you would have gotten bugcheck `0x139` = `KERNEL_SECURITY_CHECK_FAILURE` with code `0x6` = `FAST_FAIL_GS_COOKIE_INIT`.
- If the above failed, the function simply triggers a breakpoint. This is what you are seeing.

Homework questions:
- (difficulty: easy) Why is the value of `__security_cookie` always `0x2B992DDFA232` on Windows 7 and 8.0 if the target OS is set to 8.1 or greater at compile time?
- (difficulty: medium) Why is the value of `__security_cookie` **not** `0x2B992DDFA232` on Windows 8.1 and later when using the exact same driver file?
- (difficulty: medium) Where does `__security_init_cookie` come from anyway, and what's so different about the Windows 7 version of this function that it doesn't crash?
- (difficulty: hard) Why did I waste my time writing this? Both the README file and my first reply to this thread clearly state that PPLKiller does not support Windows 7, because it was made to solve an issue that does not even exist on that OS. You are using the wrong tool for the job.

**Comment by fatrolls** [comment]
well thank you for the write-up i just thought I could help you with the crash bug if it existed didn't know it was a compile issue.

Thanks i'll look into different solutions
